name: ci

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:     
      -
        name: Checkout 
        uses: actions/checkout@v2
      - name: Set variables
        id: meta
        run: |
          if [[ "${{github.event_name}}" == "release" ]]; then
            echo "::set-output name=tag::${{ github.event.release.tag_name }}"
          else
            echo "::set-output name=tag::latest"
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/serialization-benchmark:${{ steps.meta.outputs.tag }}
